In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
import sklearn.tree as tree
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
!cp /content/drive/MyDrive/kaggle/df_utils.py /content/
import df_utils

In [ ]:
def preprocess(df):
    df = df.copy()

    # def normalize_name(x):
    #     return " ".join([v.strip(",()[].\"'") for v in x.split(" ")])

    def ticket_number(x):
        return x.split(" ")[-1]

    def ticket_item(x):
        items = x.split(" ")
        if len(items) == 1:
            return "NONE"
        return "_".join(items[0:-1])

    # df["Name"] = df["Name"].apply(normalize_name)
    df["Ticket_number"] = df["Ticket"].apply(ticket_number)
    df["Ticket_item"] = df["Ticket"].apply(ticket_item)
    return df

In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/kaggle/titanic/train.csv')
#print(df_train.head(10))

df_train_x = df_train.drop(['PassengerId', 'Name', 'Cabin'], axis=1)

# Categorical values to numeric
df_train_x = df_utils.one_hot_encoding(df_train_x, "Sex")
label_encoder = preprocessing.LabelEncoder()
df_train_x['Embarked']= label_encoder.fit_transform(df_train_x['Embarked'])

# Fix NaN
# print(df_train_x.isna().any())
# df_utils.fill_with_mean("Age", df_train_x)
# df_utils.fill_with_mode("Embarked", df_train_x)

df_train_x = preprocess(df_train_x)
df_train_x = df_train_x.drop(['Ticket'], axis=1)
df_train_x['Ticket_item']= label_encoder.fit_transform(df_train_x['Ticket_item'])
df_train_x.Ticket_number = pd.to_numeric(df_train_x.Ticket_number, errors='coerce')

df_train_x = df_train_x.dropna()
df_train_x = df_train_x.reset_index(drop=True)

# print(f"df_train_x.shape[0] = {df_train_x.shape[0]}")
print(df_train_x.head(10))

   Survived  Pclass   Age  SibSp  Parch     Fare  Embarked  Sex_female  \
0         0       3  22.0      1      0   7.2500         2         0.0   
1         1       1  38.0      1      0  71.2833         0         1.0   
2         1       3  26.0      0      0   7.9250         2         1.0   
3         1       1  35.0      1      0  53.1000         2         1.0   
4         0       3  35.0      0      0   8.0500         2         0.0   
5         0       1  54.0      0      0  51.8625         2         0.0   
6         0       3   2.0      3      1  21.0750         2         0.0   
7         1       3  27.0      0      2  11.1333         2         1.0   
8         1       2  14.0      1      0  30.0708         0         1.0   
9         1       3   4.0      1      1  16.7000         2         1.0   

   Sex_male  Ticket_number  Ticket_item  
0       1.0        21171.0            4  
1       0.0        17599.0           18  
2       0.0      3101282.0           37  
3       0.0      

In [ ]:
y = df_train_x['Survived'].values
print(y[0:5])
df_train_x = df_train_x.drop(['Survived'], axis=1)

X = df_train_x.values  #.astype(float)
print(X[0:5])

X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)
print('Shape of X training set {}'.format(X_trainset.shape),'&',' Size of Y training set {}'.format(y_trainset.shape))
print('Shape of X test set {}'.format(X_testset.shape),'&','Size of y test set {}'.format(y_testset.shape))

[0 1 1 1 0]
[[3.000000e+00 2.200000e+01 1.000000e+00 0.000000e+00 7.250000e+00
  2.000000e+00 0.000000e+00 1.000000e+00 2.117100e+04 4.000000e+00]
 [1.000000e+00 3.800000e+01 1.000000e+00 0.000000e+00 7.128330e+01
  0.000000e+00 1.000000e+00 0.000000e+00 1.759900e+04 1.800000e+01]
 [3.000000e+00 2.600000e+01 0.000000e+00 0.000000e+00 7.925000e+00
  2.000000e+00 1.000000e+00 0.000000e+00 3.101282e+06 3.700000e+01]
 [1.000000e+00 3.500000e+01 1.000000e+00 0.000000e+00 5.310000e+01
  2.000000e+00 1.000000e+00 0.000000e+00 1.138030e+05 1.600000e+01]
 [3.000000e+00 3.500000e+01 0.000000e+00 0.000000e+00 8.050000e+00
  2.000000e+00 0.000000e+00 1.000000e+00 3.734500e+05 1.600000e+01]]
Shape of X training set (497, 10) &  Size of Y training set (497,)
Shape of X test set (213, 10) & Size of y test set (213,)


In [ ]:
decTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
decTree

decTree.fit(X_trainset,y_trainset)

tree = decTree.predict(X_testset)
print(tree[0:5])
print(y_testset[0:5])

from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, tree))

[0 0 1 1 0]
[0 1 1 1 0]
DecisionTrees's Accuracy:  0.8262910798122066


In [ ]:
df_test = pd.read_csv('/content/drive/MyDrive/kaggle/titanic/test.csv')
#print(df_train.head(10))

df_test_x = df_test.drop(['PassengerId', 'Name', 'Cabin'], axis=1)

# Categorical values to numeric
df_test_x = df_utils.one_hot_encoding(df_test_x, "Sex")
label_encoder = preprocessing.LabelEncoder()
df_test_x['Embarked']= label_encoder.fit_transform(df_test_x['Embarked'])

df_test_x = preprocess(df_test_x)
df_test_x = df_test_x.drop(['Ticket'], axis=1)
df_test_x['Ticket_item']= label_encoder.fit_transform(df_test_x['Ticket_item'])
df_test_x.Ticket_number = pd.to_numeric(df_test_x.Ticket_number, errors='coerce')

# Fix NaN
# print(df_test_x.isna().any())
df_utils.fill_with_mean("Age", df_test_x)
df_utils.fill_with_mean("Fare", df_test_x)

# print(f"df_test_x.shape[0] = {df_test_x.shape[0]}")
print(df_test_x.head(10))

Pclass           False
Age               True
SibSp            False
Parch            False
Fare              True
Embarked         False
Sex_female       False
Sex_male         False
Ticket_number    False
Ticket_item      False
dtype: bool
   Pclass   Age  SibSp  Parch     Fare  Embarked  Sex_female  Sex_male  \
0       3  34.5      0      0   7.8292         1         0.0       1.0   
1       3  47.0      1      0   7.0000         2         1.0       0.0   
2       2  62.0      0      0   9.6875         1         0.0       1.0   
3       3  27.0      0      0   8.6625         2         0.0       1.0   
4       3  22.0      1      1  12.2875         2         1.0       0.0   
5       3  14.0      0      0   9.2250         2         0.0       1.0   
6       3  30.0      0      0   7.6292         1         1.0       0.0   
7       2  26.0      1      1  29.0000         2         0.0       1.0   
8       3  18.0      0      0   7.2292         0         1.0       0.0   
9       3  21.0   

In [ ]:
X = df_test_x.values  #.astype(float)
print(X[0:5])

y_ = decTree.predict(X)
print(tree[0:5])

[[3.000000e+00 3.450000e+01 0.000000e+00 0.000000e+00 7.829200e+00
  1.000000e+00 0.000000e+00 1.000000e+00 3.309110e+05 1.500000e+01]
 [3.000000e+00 4.700000e+01 1.000000e+00 0.000000e+00 7.000000e+00
  2.000000e+00 1.000000e+00 0.000000e+00 3.632720e+05 1.500000e+01]
 [2.000000e+00 6.200000e+01 0.000000e+00 0.000000e+00 9.687500e+00
  1.000000e+00 0.000000e+00 1.000000e+00 2.402760e+05 1.500000e+01]
 [3.000000e+00 2.700000e+01 0.000000e+00 0.000000e+00 8.662500e+00
  2.000000e+00 0.000000e+00 1.000000e+00 3.151540e+05 1.500000e+01]
 [3.000000e+00 2.200000e+01 1.000000e+00 1.000000e+00 1.228750e+01
  2.000000e+00 1.000000e+00 0.000000e+00 3.101298e+06 1.500000e+01]]
[0 0 0 0 1]


In [ ]:
predictions = pd.DataFrame({
        "PassengerId": df_test["PassengerId"],
        "Survived": y_
    })

def make_submission(predictions):
    path="/content/drive/MyDrive/kaggle/titanic/submission.csv"
    predictions.to_csv(path, index=False)
    print(f"Submission exported to {path}")

make_submission(predictions)

Submission exported to /content/drive/MyDrive/kaggle/titanic/submission.csv
